
export const  blog = [
    {   id : 1,
        title : "Fashion Kara kro ",
        description : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi doloribus, quae ad et blanditiis perferendis pariatur, praesentium magni, necessitatibus maxime hic nisi ratione voluptatibus ipsum corporis neque. Eaque, quo blanditiis?",
        image :  "../assests/images/fashion.jpg" ,
        view : 10,
        tags_id : "Fashion",
    },
    {   id : 2,
        title : "Health ka dhyan rakho ",
        description : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi doloribus, quae ad et blanditiis perferendis pariatur, praesentium magni, necessitatibus maxime hic nisi ratione voluptatibus ipsum corporis neque. Eaque, quo blanditiis?",
        image :  "../assests/images/health.jpg" ,
        view : 10,
        tags_id : "Health",
    },
    {   id : 3,
        title : "Technology is the best ",
        description : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi doloribus, quae ad et blanditiis perferendis pariatur, praesentium magni, necessitatibus maxime hic nisi ratione voluptatibus ipsum corporis neque. Eaque, quo blanditiis?",
        image :  "../assests/images/techno.jpg" ,
        view : 10,
        tags_id : "Technology",
    },
    {   id : 4,
        title : "Ghumo firo jindgi kato",
        description : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi doloribus, quae ad et blanditiis perferendis pariatur, praesentium magni, necessitatibus maxime hic nisi ratione voluptatibus ipsum corporis neque. Eaque, quo blanditiis?",
        image :  "../assests/images/travel.jpg" ,
        view : 10,
        tags_id : "Travel",
    },
   
]